import React, { useState } from 'react';
import axios from 'axios';
import { useSelector, useDispatch } from 'react-redux';
import { mergeComplaintData, updateField, resetComplaint } from './store/complaintSlice';
import './App.css';
import jsPDF from 'jspdf';

function App() {
  const [messages, setMessages] = useState([
    { sender: 'ai', text: 'Hello! I am your AIVOA QMS Copilot. Paste your complaint text below, upload a document, or chat with me to auto-fill the form.' }
  ]);
  const [inputMessage, setInputMessage] = useState('');
  const [loading, setLoading] = useState(false);
  const [uploading, setUploading] = useState(false);

  // Redux state
  const formData = useSelector(state => state.complaint);
  const dispatch = useDispatch();

  const handleSendMessage = async (e) => {
    e.preventDefault();
    if (!inputMessage.trim()) return;

    const userMsg = inputMessage;
    setMessages(prev => [...prev, { sender: 'user', text: userMsg }]);
    setInputMessage('');
    setLoading(true);

    try {
      const response = await axios.post('http://127.0.0.1:8000/api/chat', {
        message: userMsg
      });

      if (response.data.status === 'success') {
        const aiData = response.data.ai_response;

        // Smart Merge Logic via Redux action
        dispatch(mergeComplaintData(aiData));

        setMessages(prev => [
          ...prev,
          { sender: 'ai', text: 'Complaint analyzed! Form has been updated.' }
        ]);
      } else {
        setMessages(prev => [...prev, { sender: 'ai', text: 'Error processing complaint.' }]);
      }
    } catch (err) {
      setMessages(prev => [...prev, { sender: 'ai', text: 'Failed to connect to backend server. Is FastAPI running?' }]);
    } finally {
      setLoading(false);
    }
  };

  const handleFormChange = (e) => {
    dispatch(updateField({ name: e.target.name, value: e.target.value }));
  };

  const handleSaveToDB = async () => {
    try {
      const response = await axios.post('http://127.0.0.1:8000/api/save_complaint', formData);
      if (response.data.status === 'success') {
        let msg = '🎉 Complaint successfully saved to database! ID: ' + response.data.id;
        if (response.data.duplicate_warning) {
          msg += '\n\n' + response.data.duplicate_warning;
        }
        alert(msg);
        setMessages(prev => [...prev, { sender: 'ai', text: 'Complaint has been officially logged in the system database.' }]);
      } else {
        alert('Error saving data: ' + response.data.message);
      }
    } catch (err) {
      alert('Failed to connect to backend while saving. Please check if FastAPI is running.');
      console.error(err);
    }
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("AIVOA QMS - Official Complaint Report", 20, 20);
    doc.setLineWidth(0.5);
    doc.line(20, 25, 190, 25);

    // Body Content
    doc.setFontSize(12);
    let yPos = 35;

    const addPdfRow = (label, value) => {
      doc.setFont("helvetica", "bold");
      doc.text(`${label}:`, 20, yPos);
      doc.setFont("helvetica", "normal");
      
      const splitText = doc.splitTextToSize(value || "N/A", 120);
      doc.text(splitText, 70, yPos);
      yPos += (splitText.length * 7) + 4;
    };

    addPdfRow("Product Name", formData.product_name);
    addPdfRow("Batch Number", formData.batch_number);
    addPdfRow("Originating Site", formData.originating_site);
    addPdfRow("Impacted NPM", formData.impacted_npm);
    addPdfRow("Complaint Category", formData.complaint_category);
    addPdfRow("Severity", formData.severity);
    addPdfRow("Product Defect", formData.product_defect);
    addPdfRow("Complaint Desc", formData.complaint_description);
    addPdfRow("Suggested Action", formData.suggested_next_action);
    addPdfRow("Risk Assessment", formData.initial_risk_assessment);

    // Footer
    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    doc.text(`Generated by AIVOA AI Copilot on ${new Date().toLocaleDateString()}`, 20, 280);

    const fileName = formData.batch_number ? `QMS_Report_${formData.batch_number}.pdf` : `QMS_Report.pdf`;
    doc.save(fileName);
  };

  const handleReset = () => {
    dispatch(resetComplaint());
    setMessages([
      { sender: 'ai', text: 'Hello! I am your AIVOA QMS Copilot. Paste your complaint text below, upload a document, or chat with me to auto-fill the form.' }
    ]);
  };

  const handleEditMessage = (text) => {
    setInputMessage(text);
  };

  // PDF/Document Upload Handler
  const handleFileUpload = async (e) => {
    const file = e.target.files[0];
    if (!file) return;

    setUploading(true);
    setMessages(prev => [...prev, { sender: 'user', text: `📎 Uploaded document: ${file.name}` }]);

    const uploadFormData = new FormData();
    uploadFormData.append('file', file);

    try {
      const response = await axios.post('http://127.0.0.1:8000/api/upload_document', uploadFormData, {
        headers: { 'Content-Type': 'multipart/form-data' }
      });

      if (response.data.status === 'success') {
        const aiData = response.data.ai_response;
        dispatch(mergeComplaintData(aiData));
        setMessages(prev => [...prev, { sender: 'ai', text: 'Document processed successfully! Form has been updated from the uploaded file.' }]);
      } else {
        setMessages(prev => [...prev, { sender: 'ai', text: 'Error processing document: ' + (response.data.exact_error_message || 'Unknown error') }]);
      }
    } catch (err) {
      setMessages(prev => [...prev, { sender: 'ai', text: 'Failed to upload document. Check backend connection.' }]);
      console.error(err);
    } finally {
      setUploading(false);
      e.target.value = null; // reset file input taaki same file dobara upload ho sake
    }
  };

  return (
    <div style={{ display: 'flex', height: '100vh', fontFamily: "'Inter', sans-serif", backgroundColor: '#f4f6f9' }}>

      {/* LEFT SIDE: QMS FORM */}
      <div style={{ flex: 1, padding: '25px', overflowY: 'auto', borderRight: '1px solid #ddd', backgroundColor: '#fff' }}>
        <h2 style={{ color: '#2c3e50', marginBottom: '20px' }}>📋 AIVOA QMS - Complaint Form</h2>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' }}>
          <div><label style={labelStyle}>Product Name</label><input type="text" name="product_name" value={formData.product_name} onChange={handleFormChange} style={inputStyle} /></div>
          <div><label style={labelStyle}>Batch Number</label><input type="text" name="batch_number" value={formData.batch_number} onChange={handleFormChange} style={inputStyle} /></div>
          <div><label style={labelStyle}>Originating Site</label><input type="text" name="originating_site" value={formData.originating_site} onChange={handleFormChange} style={inputStyle} /></div>
          <div><label style={labelStyle}>Impacted NPM</label><input type="text" name="impacted_npm" value={formData.impacted_npm} onChange={handleFormChange} style={inputStyle} /></div>
          <div><label style={labelStyle}>Complaint Category</label><input type="text" name="complaint_category" value={formData.complaint_category} onChange={handleFormChange} style={inputStyle} /></div>
          <div><label style={labelStyle}>Severity</label><input type="text" name="severity" value={formData.severity} onChange={handleFormChange} style={inputStyle} /></div>
        </div>
        <div style={{ marginTop: '15px' }}><label style={labelStyle}>Product Defect</label><input type="text" name="product_defect" value={formData.product_defect} onChange={handleFormChange} style={inputStyle} /></div>
        <div style={{ marginTop: '15px' }}><label style={labelStyle}>Complaint Description</label><textarea name="complaint_description" value={formData.complaint_description} onChange={handleFormChange} rows="3" style={{ ...inputStyle, resize: 'vertical' }} /></div>
        <div style={{ marginTop: '15px' }}><label style={labelStyle}>Suggested Next Action</label><textarea name="suggested_next_action" value={formData.suggested_next_action} onChange={handleFormChange} rows="2" style={{ ...inputStyle, resize: 'vertical' }} /></div>
        <div style={{ marginTop: '15px' }}><label style={labelStyle}>Initial Risk Assessment</label><textarea name="initial_risk_assessment" value={formData.initial_risk_assessment} onChange={handleFormChange} rows="2" style={{ ...inputStyle, resize: 'vertical' }} /></div>

        <div style={{ display: 'flex', gap: '10px', marginTop: '20px' }}>
          <button onClick={handleSaveToDB} style={{ flex: 1, padding: '12px', backgroundColor: '#27ae60', color: '#fff', border: 'none', borderRadius: '5px', cursor: 'pointer', fontWeight: 'bold' }}>
            💾 Save to DB
          </button>

          <button onClick={handleDownloadPDF} style={{ flex: 1, padding: '12px', backgroundColor: '#8e44ad', color: '#fff', border: 'none', borderRadius: '5px', cursor: 'pointer', fontWeight: 'bold' }}>
            📄 Download PDF
          </button>

          <button onClick={handleReset} style={{ flex: 1, padding: '12px', backgroundColor: '#e74c3c', color: '#fff', border: 'none', borderRadius: '5px', cursor: 'pointer', fontWeight: 'bold' }}>
            🔄 New Complaint
          </button>
        </div>
      </div>

      {/* RIGHT SIDE: AI COPILOT CHAT */}
      <div style={{ width: '400px', display: 'flex', flexDirection: 'column', backgroundColor: '#fff' }}>
        <div style={{ padding: '20px', backgroundColor: '#2c3e50', color: '#fff', fontWeight: 'bold' }}>🤖 AI Copilot Chat</div>

        <div style={{ flex: 1, padding: '15px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '15px' }}>
          {messages.map((msg, index) => (
            <div key={index} style={{ display: 'flex', flexDirection: 'column', alignItems: msg.sender === 'user' ? 'flex-end' : 'flex-start' }}>
              <div style={{
                backgroundColor: msg.sender === 'user' ? '#3498db' : '#ecf0f1',
                color: msg.sender === 'user' ? '#fff' : '#333',
                padding: '10px 14px', borderRadius: '8px', maxWidth: '85%', fontSize: '14px', lineHeight: '1.4', whiteSpace: 'pre-wrap'
              }}>
                {msg.text}
              </div>

              {msg.sender === 'user' && !msg.text.startsWith('📎') && (
                <button
                  onClick={() => handleEditMessage(msg.text)}
                  style={{ marginTop: '4px', fontSize: '11px', color: '#3498db', background: 'none', border: 'none', cursor: 'pointer', padding: '0' }}
                >
                  ✏️ Edit
                </button>
              )}
            </div>
          ))}
          {loading && <div style={{ fontStyle: 'italic', color: '#888', fontSize: '13px' }}>AI is analyzing complaint...</div>}
          {uploading && <div style={{ fontStyle: 'italic', color: '#888', fontSize: '13px' }}>📄 Extracting document...</div>}
        </div>

        {/* File Upload Row */}
        <div style={{ padding: '10px 15px', borderTop: '1px solid #eee', backgroundColor: '#f9f9f9' }}>
          <label style={{
            display: 'inline-flex', alignItems: 'center', gap: '6px',
            fontSize: '13px', color: '#2c3e50', cursor: 'pointer',
            border: '1px dashed #bbb', borderRadius: '4px', padding: '6px 10px'
          }}>
            📎 Upload PDF Complaint
            <input type="file" accept=".pdf" onChange={handleFileUpload} style={{ display: 'none' }} />
          </label>
        </div>

        <form onSubmit={handleSendMessage} style={{ display: 'flex', padding: '15px', borderTop: '1px solid #ddd', backgroundColor: '#f9f9f9' }}>
          <input
            type="text" value={inputMessage} onChange={(e) => setInputMessage(e.target.value)}
            placeholder="Type complaint here..."
            style={{ flex: 1, padding: '10px', borderRadius: '4px', border: '1px solid #ccc', outline: 'none' }}
          />
          <button type="submit" style={{ marginLeft: '10px', padding: '10px 15px', backgroundColor: '#3498db', color: '#fff', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>
            Send
          </button>
        </form>
      </div>

    </div>
  );
}

const labelStyle = { fontWeight: 'bold', fontSize: '13px', color: '#333' };
const inputStyle = { width: '100%', padding: '8px', marginTop: '5px', borderRadius: '4px', border: '1px solid #ccc', boxSizing: 'border-box' };

export default App;